version: "3"
services:
  web:
    image: malmaud/juliaslack:latest
    build: .
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "4000:4000"
    networks:
      - frontend
    depends_on:
      - db
    volumes:
      - "${HOME}/gql/lib:/app/lib"
      - "${HOME}/gql/assets:/app/assets"
      - "${HOME}/tmp/logs:/logs"
      - "${HOME}/gql/templates:/app/templates"
      - "${HOME}/tmp/secrets:/secrets"
  db:
    image: rethinkdb:2.3.5
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - frontend
    ports:
      - "8080:8080"
    volumes:
      - "${HOME}/tmp/data:/data"
networks:
  frontend:
