version: "3"
services:
  web:
    image: malmaud/juliaslack
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "4000:4000"
    networks:
      - frontend
    depends_on:
      - db
  db:
    image: rethinkdb:2.3.5
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - frontend
    volumes:
      - "/slackinvite_data:/data"
    ports:
      - "8080:8080"
networks:
  frontend:
