apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slack-invite
      role: ingress
  template:
    metadata:
      labels:
        app: slack-invite
        role: ingress
        time: "514"
    spec:
      containers:
        - name: proxy
          image: malmaud/juliaslackproxy:1.4
          imagePullPolicy: Always
          ports:
          - containerPort: 80
            hostPort: 80
          - containerPort: 443
            hostPort: 443
          volumeMounts:
            - mountPath: /etc/letsencrypt
              readOnly: true
              name: ssl-volume
            - name: acme-challenge
              mountPath: /var/www/letsencrypt
      volumes:
        - name: ssl-volume
          hostPath:
           type: Directory
           path: /etc/letsencrypt
        - name: acme-challenge
          hostPath:
            type: DirectoryOrCreate
            path: /etc/acme

