apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ssl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slack-invite
      role: ssl
  template:
    metadata:
      labels:
        app: slack-invite
        role: ssl
        time: "527"
    spec:
      containers:
        - name: ssl
          image: malmaud/juliaslackssl:1.0
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /etc/letsencrypt
              name: ssl-volume
            - name: acme-challenge
              mountPath: /var/www/letsencrypt
      volumes:
        - name: ssl-volume
          hostPath:
            type: DirectoryOrCreate
            path: /etc/letsencrypt
        - name: acme-challenge
          hostPath:
            type: DirectoryOrCreate
            path: /etc/acme
